---

- hosts: '161.35.183.49'
  gather_facts: yes
  tasks:
  - name: "Create empty file"
    file:
      path: "/tmp/validate_provisioning_test"
      state: touch

# make sure to test with: ansible all -m command -a "ls /tmp" -i hosts
